#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: yuyc
 * Date: 2016/8/18
 * Time: 18:05
 */

error_reporting(-1);
define('ROOT', realpath(__DIR__));

$shortOpts = '';
$shortOpts .= 'l:';   # the log path
$shortOpts .= 's:';
$shortOpts .= 'vhd';  # -v: debug -h: help -d: daemonize

# longoption
$longOpts = [
    'debug',
    'help',
];
$options = getopt($shortOpts, $longOpts);

if (empty($options)) {
    goto help;
}

# debug
define('IS_DEBUG',  isset($options['debug']) || isset($options['v']));
# log
define('LOG_PATH',  isset($options['l']) && $options['l'] ? $options['l'] : '/var/log/php_crond.log');
# config
define('CONFIG_FILE', isset($options['c']) && $options['c'] ? $options['c'] : '/etc/crontab.ini');
# log level
define('INFO', 1);
define('DEBUG', 2);
define('WARN', 3);

if ( ! is_file(CONFIG_FILE) ) {
    if ( !is_file(ROOT . '/crontab.ini.default') ) {
        info('配置文件不存在', WARN);
        return false;
    }
    if ( ! @copy(ROOT . '/crontab.ini.default', '/etc/crontab.ini') ) {
        info('请使用root用户启动', WARN);
    }
}

$config = parse_ini_file(CONFIG_FILE, true);

define('IS_DAEMON', $config['server']['daemonize']);

include './lib/Server.php';
$server = new Server();
$cmdParam = isset($options['s']) && $options['s'] ? $options['s'] : null;
switch ($cmdParam) {
    case 'start':
        $server->start();
        break;
    case 'stop':
        $server->stop();
        break;
    case 'reload':
        $server->reload();
        break;
    default:
        goto help;
}
return true;

help:
$sbinName = basename(__FILE__);
echo <<<EOF
    Usage: $sbinName [options]
    -s            start | stop | reload
    -l            the log path
    -v, --debug   open debug mode
    -h, --help    show help info

EOF;
exit;

function info($info, $log_level = 1)
{
    switch ($log_level) {
        case INFO:
            $begin = "\x1b[33m";
            $tag = 'info';
            break;
        case DEBUG:
            //如果不是debug模式，则不记录
            if (! IS_DEBUG) return false;
            $begin = "\x1b[34m";
            $tag = 'debug';
            break;
        case WARN:
            $begin = "\x1b[31m";
            $tag = 'warn';
    }
    $end = "\x1b[39m";

    $str = $begin . date('[Y-m-d H:i:s]') . " [$tag]{$end} - $info\n";
    if (IS_DAEMON) {
        file_put_contents(LOG_PATH, $str, FILE_APPEND);
    } else {
        echo $str;
    }
}





